export const SET_AUTH = 'SET_AUTH'
export const LOG_OUT = 'LOG_OUT'


export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const CHANGE_CART_ITEM_QUANTITY = 'CHANGE_CART_ITEM_QUANTITY'
export const CHANGE_CART_ITEM_SIZE = 'CHANGE_CART_ITEM_SIZE'
export const CLEAR_CART = 'CLEAR_CART'


export const CREATE_BILL = 'CREATE_BILL'


//waiting order
export const CREATE_WAITING_ORDER = 'CREATE_WAITING_ORDER'
export const DELETE_WAITING_ORDER = 'DELETE_WAITING_ORDER'
export const UPDATE_WAITING_ORDER_DETAIL = 'UPDATE_WAITING_ORDER_DETAIL'
export const UPDATE_WAITING_ORDER_USER = 'UPDATE_WAITING_ORDER_USER'